name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run start
        env:
          CI: true

  deploy:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies & Build App
        run: ./.github/workflows/build.sh prod
        shell: bash
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.5.3
        with:
          local: dist
          remote: /var/www/test-deploy
          host: berrybox.tv
          username: root
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

