name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run start
        env:
          CI: true

  deploy:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies & Build App
        run: |
          cp ./.github/workflows/environments/environment.prod.ts ./src/environments/environment.prod.ts
          npm install
          npx ng build --aot --prod --no-progress
      - name: Clean Dist folder
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY}} ${{ secrets.USER }}@${{ secrets.HOST }}
          rm -rf /var/www/test-deploy/
      - name: Deploy via SCP
        uses: horochx/deploy-via-scp@v1.0.1
        with:
          local: dist
          remote: /var/www/test-deploy/dist
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}



